name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
         persist-credentials: false
         fetch-depth: 0

      - name: Push to Wiki
        run: |
          git push -q https://Richasy:${{ secrets.GITHUB_TOKEN }}@github.com/Richasy/FantasyCopilot.wiki.git main:master --force