name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
         token: ${{ secrets.PERSON_ACCESS_TOKEN }}

      - name: Push to Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: ""
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSON_ACCESS_TOKEN }}