name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
         token: ${{ secrets.PERSON_ACCESS_TOKEN }}

      - name: Push to Wiki
        run: |
          git push -q https://Richasy:${{ secrets.PERSON_ACCESS_TOKEN }}@github.com/Richasy/FantasyCopilot.wiki.git main:master --force